version: '3.8'
services:
  dev-db:
    image: postgres:15-alpine
    container_name: postgresdb
    ports:
      - 9999:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: assuresoftdb
    networks:
      - assuresoftnet
networks:
  assuresoftnet: