version: '3.8'
services:
  dev-db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maria17
      POSTGRES_DB: assuresoft
    networks:
      - assuresoftnet
networks:
  assuresoftnet: